var AppConstants = {
    ADD_ITEM: 'ADD_ITEM',
    REMOVE_ITEM: 'REMOVE_ITEM',
    UPDATE_ITEM_TEXT: 'UPDATE_ITEM_TEXT',
    HANDLE_SUBMIT: 'HANDLE_SUBMIT',
    CHANGE: 'CHANGE',
    EDIT_ITEM: 'EDIT_ITEM',
    EDIT_ITEM_TEXT: 'EDIT_ITEM_TEXT',
    HANDLE_INDIVIDUAL_ITEM_SUBMIT: 'HANDLE_INDIVIDUAL_ITEM_SUBMIT',
    TOGGLE_ITEM_STATE: 'TOGGLE_ITEM_STATE',
    CLEAR_COMPLETED_ITEMS: 'CLEAR_COMPLETED_ITEMS',
    FILTER_ROUTES: 'FILTER_ROUTES'
};

module.exports = AppConstants;